#ifdef BABY_CARE_BUILD_MAIN_EXAMPLE

#include "main.h"
#include "baby_care_app.h"

/*
 * Copy the three marked calls into the CubeMX generated main.c.
 * Keep SystemClock_Config(), MX_GPIO_Init(), MX_TIMx_Init() and MX_USARTx_Init()
 * generated by CubeMX.
 */

int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_TIM2_Init();
    MX_TIM3_Init();
    MX_USART1_UART_Init();
    MX_USART2_UART_Init();

    BabyCare_Init();

    while (1) {
        BabyCare_Task();
    }
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    BabyCare_OnUartRxComplete(huart);
}

#endif
